### ISSUE TITLE
On latest build app shows as white screen

### ISSUE THREAD

**Issue by KorakSilvercloud** [AsteroidOS/asteroid-alarmclock#2] opened 2017-03-21 20:28 UTC
On latest dory build this app opens as solid white screen.

**Comment by TheLastProject** [comment] 2017-03-21 20:30
That's not a bug specific to this app. Sometimes, for some reason, AsteroidOS just stops drawing the app. The preview will still draw though and all buttons will work, it just sometimes draws plain white for some reason but I never found a reliable way to reproduce it.

**Comment by KorakSilvercloud** [comment] 2017-03-23 15:48
On my current build I am seeing this consistently. I have rebooted and still see the issue, seems to only be for this app. The app also shows as solid white on the task manager screen as well.

**Comment by KorakSilvercloud** [comment] 2017-03-23 15:52
One thought that came to mind. Is this app possibly using qtgraphicaleffects? That was removed in recent builds and could possibly be related?

**Comment by FlorentRevest** [comment] 2017-03-23 18:57
I don't think it uses qtgraphicaleffects but it may be an explanation indeed. Could you please share the result of an adb shell journalctl -u user@1000 --no-pager please ?

**Comment by KorakSilvercloud** [comment] 2017-03-23 19:15
Here is the result of that command. 

[log.txt](https://github.com/AsteroidOS/asteroid-alarmclock/files/865895/log.txt)

**Comment by FlorentRevest** [comment] 2017-03-29 19:46
This has been fixed with https://github.com/AsteroidOS/qml-asteroid/commit/2af8e4168fa7f4efa3f5528f1075eab5424866db

**Closed as completed by FlorentRevest** 2017-03-29 19:46 UTC
